{
 "title": "FV - Statistiche",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "content": "<center><h1>Totale Impianto</h1></center>\n\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "content": "<center><h1>Totale Impianto - Time Range</h1></center>\n\n\n\n\n"
  },
  {
   "title": "Prelievo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT last(\"value\") - 67.02 FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  },
  {
   "title": "Immissione",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT last(\"value\") FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  },
  {
   "title": "%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 4, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT  (mean(\"immissione\") / mean(\"produzione\") ) * 100 as \"percimmissione\"   FROM\n( \nSELECT last(\"value\") - 67.02 as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import')\n), \n(\nSELECT last(\"value\")  as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') \n),\n(\nSELECT last(\"value\") -20.22 as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') \n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  },
  {
   "title": "Produzione",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT last(\"value\") -20.22 FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  },
  {
   "title": "Autoconsumo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT  mean(\"produzione\") - mean(\"immissione\") as \"consumo\"  FROM\n(\nSELECT last(\"value\")  as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') \n),\n(\nSELECT last(\"value\") -20.22 as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') \n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  },
  {
   "title": "%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 9, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT   (mean(\"produzione\") - mean(\"immissione\")) / (mean(\"prelievo\") + mean(\"produzione\")  - mean(\"immissione\")) * 100 as \"percautoconsumo\"    FROM\n( \nSELECT last(\"value\") - 67.02 as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import')\n), \n(\nSELECT last(\"value\")  as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') \n),\n(\nSELECT last(\"value\") -20.22 as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') \n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  },
  {
   "title": "Consumo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT mean(\"prelievo\") + mean(\"produzione\") - mean(\"immissione\") as \"consumo\"  FROM\n( \nSELECT last(\"value\") - 67.02 as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import')\n), \n(\nSELECT last(\"value\")  as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') \n),\n(\nSELECT last(\"value\") -20.22 as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') \n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  },
  {
   "title": "Prelievo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT last(\"value\") - first(\"value\") FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  },
  {
   "title": "Immissione",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT last(\"value\") - first(\"value\") FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  },
  {
   "title": "%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 16, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT  (mean(\"immissione\") / mean(\"produzione\") ) * 100 as \"percimmissione\"   FROM\n( \nSELECT last(\"value\") - first(\"value\")  as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter \n), \n(\nSELECT last(\"value\") - first(\"value\") as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter \n),\n(\nSELECT last(\"value\") - first(\"value\") as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  },
  {
   "title": "Produzione",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT last(\"value\") - first(\"value\") FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  },
  {
   "title": "AutoConsumo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT mean(\"produzione\") - mean(\"immissione\") as \"autoconsumo\"  FROM\n( \nSELECT last(\"value\") - first(\"value\")  as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter \n), \n(\nSELECT last(\"value\") - first(\"value\") as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter \n),\n(\nSELECT last(\"value\") - first(\"value\") as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  },
  {
   "title": "%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 21, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT (mean(\"produzione\") - mean(\"immissione\")) / (mean(\"prelievo\") + mean(\"produzione\")  - mean(\"immissione\")) * 100 as \"percautoconsumo\"  FROM\n( \nSELECT last(\"value\") - first(\"value\")  as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter \n), \n(\nSELECT last(\"value\") - first(\"value\") as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter \n),\n(\nSELECT last(\"value\") - first(\"value\") as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  },
  {
   "title": "Consumo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT mean(\"prelievo\") + mean(\"produzione\") - mean(\"immissione\") as \"consumo\"  FROM\n( \nSELECT last(\"value\") - first(\"value\")  as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter \n), \n(\nSELECT last(\"value\") - first(\"value\") as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter \n),\n(\nSELECT last(\"value\") - first(\"value\") as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  },
  {
   "title": "Utilizzo Giornaliero - Time Range",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "prelievo",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "immissione",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Export" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "produzione",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "consumo",
     "expression": "A['prelievo'] + C['produzione'] - B['immissione']",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "consumo",
     "periods": 7,
     "query": "SELECT mean(\"prelievo\") + mean(\"produzione\") - mean(\"immissione\") as \"consumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    },
    {
     "alias": "autoconsumo",
     "expression": "C['produzione'] - B['immissione']",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "autoconsumo",
     "periods": 7,
     "query": "SELECT mean(\"produzione\") - mean(\"immissione\") as \"autoconsumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Utilizzo Giornaliero - Time Range",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "produzione",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ],
     "tz": "Europe/Rome"
    }
   ]
  },
  {
   "title": "Import-Export Complessivo",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 16, "w": 7, "x": 10, "y": 20 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "prelievo",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "immissione",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Export" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "produzione",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "consumo",
     "expression": "A['prelievo'] + C['produzione'] - B['immissione']",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "consumo",
     "periods": 7,
     "query": "SELECT mean(\"prelievo\") + mean(\"produzione\") - mean(\"immissione\") as \"consumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    },
    {
     "alias": "autoconsumo",
     "expression": "C['produzione'] - B['immissione']",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "autoconsumo",
     "periods": 7,
     "query": "SELECT mean(\"produzione\") - mean(\"immissione\") as \"autoconsumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Spesa-Guadagno Complessivo",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 20 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "alias": "prelievo",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) *0.20 FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*0.20" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "immissione",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) *0.10 FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*0.10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Export" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "produzione",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) *0.20 FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*0.20" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "consumo",
     "expression": "A['prelievo'] + C['produzione'] - B['immissione']",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "consumo",
     "periods": 7,
     "query": "SELECT (mean(\"prelievo\") + mean(\"produzione\") - mean(\"immissione\")) * 0.20 as \"consumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\"))  as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    },
    {
     "alias": "autoconsumo",
     "expression": "C['produzione'] - B['immissione']",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "autoconsumo",
     "periods": 7,
     "query": "SELECT (mean(\"produzione\") - mean(\"immissione\")) * 0.20 as \"autoconsumo\"  FROM\n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Import-Export Giornaliero",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "prelievo",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "immissione",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Export" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "produzione",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "consumo",
     "expression": "A['prelievo'] + C['produzione'] - B['immissione']",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "consumo",
     "periods": 7,
     "query": "SELECT mean(\"prelievo\") + mean(\"produzione\") - mean(\"immissione\") as \"consumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    },
    {
     "alias": "autoconsumo",
     "expression": "C['produzione'] - B['immissione']",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "autoconsumo",
     "periods": 7,
     "query": "SELECT mean(\"produzione\") - mean(\"immissione\") as \"autoconsumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ]
    }
   ]
  }
 ]
}