{
 "title": "FV - Completo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Prelievo/Immissione",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "PowerL1" }
     ]
    }
   ]
  },
  {
   "title": "Produzione",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "PowerL1" }
     ]
    }
   ]
  },
  {
   "title": "Consumo Totale",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expression": "A['sdm_cs'] + ( B['sdm_fv'] > 0 ? B['sdm_fv'] : 0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "consumo",
     "periods": 7,
     "query": "SELECT mean(\"sdm_cs\") + mean(\"sdm_fv\") as \"consumomax\"  FROM\n( \nSELECT last(\"value\") as \"sdm_cs\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'PowerL1') AND $timeFilter GROUP BY time($__interval) fill(previous)\n), \n(\nSELECT last(\"value\") as \"sdm_fv\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'PowerL1') AND \"value\" >= 0 AND  $timeFilter GROUP BY time($__interval) fill(previous)\n)\nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Produzione, Immissione, Consumo",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "prelievo_immissione",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'PowerL1') AND $timeFilter GROUP BY time($__interval) fill(previous) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "PowerL1" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "solare",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'PowerL1') AND $timeFilter GROUP BY time($__interval) fill(previous) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "PowerL1" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "consumo",
     "expression": "A['prelievo_immissione'] + B['solare']",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "consumo",
     "periods": 7,
     "query": "SELECT mean(\"prelievo_immissione\") + mean(\"solare\") as \"consumo\"  FROM\n( \nSELECT mean(\"value\") as  \"prelievo_immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'PowerL1') AND $timeFilter GROUP BY time($__interval) fill(previous)  tz('Europe/Rome')\n), \n(\nSELECT mean(\"value\") as \"solare\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'PowerL1')  AND $timeFilter  GROUP BY time($__interval) fill(previous) tz('Europe/Rome')\n)\nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Import-Export Giornaliero",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "prelievo",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "immissione",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Export" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "produzione",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "consumo",
     "expression": "A['prelievo'] + C['produzione'] - B['immissione']",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "consumo",
     "periods": 7,
     "query": "SELECT mean(\"prelievo\") + mean(\"produzione\") - mean(\"immissione\") as \"consumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    },
    {
     "alias": "autoconsumo",
     "expression": "C['produzione'] - B['immissione']",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "autoconsumo",
     "periods": 7,
     "query": "SELECT mean(\"produzione\") - mean(\"immissione\") as \"autoconsumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "title": "Import-Export Complessivo",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 15, "w": 5, "x": 19, "y": 20 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "prelievo",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "immissione",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Export" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "produzione",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "consumo",
     "expression": "A['prelievo'] + C['produzione'] - B['immissione']",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "consumo",
     "periods": 7,
     "query": "SELECT mean(\"prelievo\") + mean(\"produzione\") - mean(\"immissione\") as \"consumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    },
    {
     "alias": "autoconsumo",
     "expression": "C['produzione'] - B['immissione']",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "outputMetricName": "autoconsumo",
     "periods": 7,
     "query": "SELECT mean(\"produzione\") - mean(\"immissione\") as \"autoconsumo\"  FROM\n( \nSELECT difference(last(\"value\")) as \"prelievo\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n), \n(\nSELECT difference(last(\"value\")) as \"immissione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.1' AND \"type\" = 'Export') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n),\n(\nSELECT difference(last(\"value\")) as \"produzione\" FROM \"autogen\".\"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(1d) fill(null) tz('Europe/Rome')\n)\nGROUP BY time(1d) fill(null) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeshiftUnit": "days"
    }
   ]
  },
  {
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 31 },
   "targets": [
    {
     "alias": "solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT mean(\"value\") FROM \"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'PowerL1') AND $timeFilter GROUP BY time($__interval) fill(previous) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "PowerL1" }
     ],
     "tz": "Europe/Rome"
    }
   ]
  },
  {
   "title": "Produzione Giornaliera (last-difference)",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "watt", "label": "Produzione" }
   ],
   "targets": [
    {
     "alias": "Produzione Solare",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT difference(last(\"value\")) FROM \"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'Import') AND $timeFilter GROUP BY time(24h) fill(previous) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Import" }
     ],
     "tz": "Europe/Rome"
    }
   ]
  },
  {
   "title": "Solare e Voltaggio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "watt", "label": "watt" }
   ],
   "targets": [
    {
     "alias": "solare",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "PowerL1" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "SDM1.2" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "VoltageL1" }
     ],
     "tz": "Europe/Rome"
    },
    {
     "alias": "voltage-solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "VoltageL1" }
     ],
     "tz": "Europe/Rome"
    }
   ]
  },
  {
   "title": "Picco Giornaliero",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "watt", "label": "Produzione" }
   ],
   "targets": [
    {
     "alias": "Produzione Solare",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "data",
     "query": "SELECT max(\"value\") FROM \"data\" WHERE (\"device\" = 'SDM1.2' AND \"type\" = 'PowerL1') AND \"value\" > 0 AND $timeFilter GROUP BY time($__interval) fill(previous) tz('Europe/Rome')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "SDM1.2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "PowerL1" }
     ],
     "tz": "Europe/Rome"
    }
   ]
  }
 ]
}